language: C
group: travis_latest

addons:
  apt:
    packages:
    - octave

before_install:                                                         # Tasks to perform before installing
                                                                        # Create virtual screen for Arduino IDE, since CLI needs it
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :-ac -screen 0 1280x1024x16"
  - sleep 3                                                             # Wait for 3 seconds
  - export DISPLAY=:1.0

  - wget http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz       # Download Arduino IDE
  - tar xf arduino-1.8.9-linux64.tar.xz                                 # Uncompress Arduino IDE
  - sudo mv arduino-1.8.9 /usr/local/share/arduino                      # Move Arduino ide to the correct directory
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
