language: C

addons:
  apt:
    packages:
    - octave

before_install:                                                         # Tasks to perform before installing
                                                                       
  - wget http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz       # Download Arduino IDE
  - tar xf arduino-1.8.9-linux64.tar.xz                                 # Uncompress Arduino IDE
  - sudo mv arduino-1.8.9 /usr/local/share/arduino                      # Move Arduino ide to the correct directory
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
# Arduino IDE adds a lot of noise caused by network traffic, trying to firewall it off
  - sudo iptables -P INPUT DROP
  - sudo iptables -P FORWARD DROP
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -A INPUT -i lo -j ACCEPT
  - sudo iptables -A OUTPUT -o lo -j ACCEPT
  - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  - arduino --pref "boardsmanager.additional.urls=https://adafruit.github.io/arduino-board-index/package_adafruit_index.json" --save-prefs

install:                                                                # Actual installation of the AutomationShield repo
  - ln -s $PWD /usr/local/share/arduino/libraries/AutomationShield      # Install repository as a library

                      
before_script:
 - octave-cli --eval "addpath('matlab');savepath"   #Adding and saving the subdirectory to Octave path   
 
 
script:

###### MATLAB ######

#Functions#
 - octave-cli --eval "constrain(2,-1,1)"                                # Constrain
 - octave-cli --eval "map(0.5,0,1,0,100)"                               # Map

###### Arduino IDE ######
#Uno#
 - arduino --verify --board arduino:avr:uno $PWD/Blink.ino
